### ISSUE TITLE
Many tests fail from "u2f reference code"

### ISSUE THREAD

**Issue by liamjm** [google/OpenSK#399] opened 2021-11-02 01:31 UTC
## Expected Behavior
All tests pass for u2f-ref-code/u2f-tests/HID/HIDTest (https://github.com/google/u2f-ref-code)

## Actual Behavior
Several tests fail

## Steps to Reproduce the Problem

1. Clone about repo and `make all` in u2f-ref-code/u2f-tests/HID/
1. Identify HID device to test (eg `u2f-ref-code/u2f-tests/HID/list`)
1. Run tests, eg `HIDTest  /dev/hidraw3 -V` ("-V" log the frames to aid debugging).

The first error is below.
```
t+0.004> deadbeef:86[8]:52A446F93FC94A3800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< deadbeef:bf[1]:0B0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
CHECK_EQ fail at test_InitOnNonBroadcastEchoesCID[475]:r.init.cmd != U2FHID_INIT: Aborted
```

The full trace is below.

## Specifications

- Version: debian
- Platform: linux

## Appendix
The "-a" continues after errors.
`./HIDTest  /dev/hidraw3 -V -a`

Output. I haven't looked at each error in detail, but as always, some of the failures might affect later tests.
```
t+0.358< (timeout)
PASS(test_Idle())
t+0.001> ffffffff:86[8]:6840FCA3EBB8F23D00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< ffffffff:86[17]:6840FCA3EBB8F23D000000BB020100000500000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.004> ffffffff:86[8]:D3E68D3FB7660D7C00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< ffffffff:86[17]:D3E68D3FB7660D7C000000BC020100000500000000000000000000000000000000000000000000000000000000000000000000000000000000
PASS(test_Init())
t+0.004> ffffffff:86[8]:22605069E3EB926A0001B818B7BE550000C01606258C7F0000C02406258C7F0000A263F1248C7F000040B728258C7F00000000000000000000
t+0.024< ffffffff:86[17]:22605069E3EB926A000000BD020100000500000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.004> 000000bd:86[8]:BA16B2F1D9C89E4200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< 000000bd:86[17]:BA16B2F1D9C89E42000000BD020100000500000000000000000000000000000000000000000000000000000000000000000000000000000000
PASS(test_BasicInit())
t+0.004> 000000bd:bc[0]:000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< 000000bd:bf[1]:010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
PASS(test_Unknown(U2FHID_SYNC))
t+0.004> deadbeef:86[8]:099AE5F453D7312600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< deadbeef:bf[1]:0B0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
CHECK_EQ fail at test_InitOnNonBroadcastEchoesCID[475]:r.init.cmd != U2FHID_INIT: (continuing -a)
CHECK_EQ fail at test_InitOnNonBroadcastEchoesCID[476]:MSG_LEN(r) != sizeof(U2FHID_INIT_RESP): (continuing -a)
CHECK_EQ fail at test_InitOnNonBroadcastEchoesCID[477]:0 != memcmp(f.init.data, r.init.data, cs): (continuing -a)
CHECK_EQ fail at test_InitOnNonBroadcastEchoesCID[485]:cid != 0xdeadbeef: (continuing -a)
PASS(test_InitOnNonBroadcastEchoesCID())
t+0.004> 000000bd:86[8]:BDBE65752472F13500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< 000000bd:86[17]:BDBE65752472F135000000BD020100000500000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.004> 000000bd:84[1]:000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< 000000bd:bf[1]:010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
PASS(test_InitUnderLock())
t+0.004> 000000bd:81[99]:7478808ED210E18C26947D005C1B4265B6275909FE8B2FBC4994316E0722A37B9A23096C33EBF95A7F765ADB929C4148C39A51C125807D6F14
t+0.004> 000000bd:86[8]:AEDD1BD080976BA300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.032< 000000bd:86[17]:AEDD1BD080976BA3000000BD020100000500000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.004> 000000bd:00:0008A0D7D68BD0300A4700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+1.001< (timeout)
PASS(test_InitSelfAborts())
t+0.003> 000000bd:81[99]:8AE6D9262721E9C172ABE7F2285606D73322A7B3B9125659EA2CE5BA5DEF01E7D5DA0EFCFBF7BE6DA2A55FCBFB66A22E8849E1415C379A4663
t+0.004> 000000bc:86[8]:7F00C06F02A844DC00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.028< 000000bc:bf[1]:060000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
CHECK_EQ fail at test_InitOther[434]:r.init.cmd != U2FHID_INIT: (continuing -a)
CHECK_GE fail at test_InitOther[435]:MSG_LEN(r) < MSG_LEN(f2): (continuing -a)
CHECK_EQ fail at test_InitOther[436]:memcmp(&f2.init.data[0], &r.init.data[0], INIT_NONCE_SIZE) != 0: (continuing -a)
t+1.001< (timeout)
CHECK_EQ fail at test_InitOther[439]:0 != U2Fob_receiveHidFrame(device, &r, 1.0): (continuing -a)
CHECK_EQ fail at test_InitOther[440]:f.cid != r.cid: (continuing -a)
CHECK_EQ fail at test_InitOther[442]:isError(r, ERR_MSG_TIMEOUT) != true: (continuing -a)
PASS(test_InitOther())
t+0.003> 000000bd:86[8]:B641D8ADFF4550A400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.020< 000000bd:bf[1]:050000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
CHECK_EQ fail at test_BasicInit[91]:r.init.cmd != U2FHID_INIT: (continuing -a)
CHECK_EQ fail at test_BasicInit[92]:MSG_LEN(r) != sizeof(U2FHID_INIT_RESP): (continuing -a)
CHECK_EQ fail at test_BasicInit[93]:memcmp(&f.init.data[0], &r.init.data[0], INIT_NONCE_SIZE) != 0: (continuing -a)
CHECK_EQ fail at test_BasicInit[94]:r.init.data[12] != U2FHID_IF_VERSION: (continuing -a)
t+0.004> 000000bd:88[0]:000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< 000000bd:88[0]:000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
CHECK_EQ fail at test_OptionalWink[171]:isError(r, ERR_INVALID_CMD) != true: (continuing -a)
PASS(test_OptionalWink())
t+0.004> 000000bd:86[8]:A51B9F0BBDCD930600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< 000000bd:86[17]:A51B9F0BBDCD9306000000BD020100000500000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.004> 000000bd:84[1]:000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< 000000bd:bf[1]:010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
PASS(test_Lock())
t+0.004> 000000bd:81[8]:AED462E56EA848EE00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< 000000bd:81[8]:AED462E56EA848EE00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
PASS(test_Echo())
t+0.004> 000000bd:81[1024]:A9095DABB1A18767E25F14E1A564854A7F24553CF1E8439FBCA5842A4ECD18F7D675A2871729EEF98902DB2E676078E685CD2376B56616710B
t+0.004> 000000bd:00:9A9B5967B4503D29F2C4401CB23AA5B515D31C754B02FA182571CD8B873E9721D9F0898D41C6B7338BF74F3D31F4F246C70EBC1211B62A3627F7C2
t+0.004> 000000bd:01:AE3559D00F49599C8A1F53BEAA4B0DE87C02DAC3C9E97FDCFA3506305DFEF20B334BDB429534DF1F5432DDFE7DEBE6FAEDC1BDB6AA3C92A47199D4
t+0.004> 000000bd:02:CE97C7DACA12B50DA7EAECC73E1EA43C9C8F23967CE453338E8FC532005E06CFF5CDA9C0E05ECD8748B94E86D7F3C37382E609FFCA5C3258EBF78A
t+0.012> 000000bd:03:EC5690BB4B5E640B3EC2D8C50B911491690754DC893AE6880442BA5C2EB2E61A0877D553D5395F13FB37D806C9EC9832F3EC0E7D27F4052B37C088
t+0.008> 000000bd:04:65726E7F7AE554CDBA8D2CCD8864A68F2D92275F86136D033A62086699C8EEFE3A5C7DB442D182FC5EAECAE61270753F029C9E88B00C8BEA6E9450
t+0.012> 000000bd:05:075C3E05979B824BDD53CDD9B17CA3978E130DCE16A96C9E59782A44E6BE94ED1AD3F2B16E74FD4BC7CA247846C810D5DB1DA3F1C60F902088BA64
t+0.012> 000000bd:06:6E78F85C92CB4E4439C341848A0BA903527113274C30CA3EF6D9CE1661887AD000732C923E7AD6783D17FCC823A5CB7516DE9C630E66A1043F6F1B
t+0.008> 000000bd:07:A1F79571F7089D89471760BF5577BB1D9A61E80F77C6ABDAD4117BD851EAF3F2E18963D8910062D817C2976C395389D4B471E32B378F060BA081E4
t+0.012> 000000bd:08:F16CD7E34D604626F24688CA5E4A62CA83B5545769C53B94FDCA9A086A1CEC5C88C43FD52486FB16CC83E12ACD43F551F849A8610EE3F50BAD9014
t+0.012> 000000bd:09:18AC007434C4B309E93905FF0688E030562325A71B6E4F7C7D337288E0029CF8AE9D6CE26120EB4A59F04A5F792A90CF4EB5766924C5E6A1F85829
t+0.008> 000000bd:0a:D95AC6D108633EEAC45ED50FB7C659173F83A70ED15C843B8049212142794B1BD311ECDB742AC538889A474060A0579F24FEADF55A3130DB7B51FC
t+0.012> 000000bd:0b:BDCA47D89D58C478CCEF3D0577D84CB738ED0ED8110C850667B7374232883EEF5386C7F0DE8B69AB7AA6B0F27EFCA9B7E9B88FFAC414012BCB386D
t+0.012> 000000bd:0c:FDC0ACEC1332B304103F6DBBB9136BAB92685549510DD84CD1EC4DFDB8856AB54516A25948555D5994CA144EDD80F96FE84EB8395B90852D7DD22A
t+0.008> 000000bd:0d:355794EA9DAB8CF6F3E2534C761D61C4FAE1BE6AC90C220268B38895305ABF65B2534F4FFEDC45F2BE983E34B59FF9AF80B71949C33C4C2BEFD4C0
t+0.012> 000000bd:0e:1F2E7F84E0D3D32FD1AF74C36D0C02A2C1A19B7122528A6B15C6B741B58B01D4BA81589A542CCA25DB3EE9494BEBEB0C8C867DAED8081AEDCED12E
t+0.008> 000000bd:0f:845D305817B1B1B105DD7B2AB8BA130105FEEC118B728F394A975338652566E98296429947F34A4CD0C67788808A8A8589769614E9254D33BCA16B
t+0.012> 000000bd:10:22C6D20B48684DE1B0402BFC10F1739971FE23F687998DEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
t+0.196< 000000bd:81[1024]:A9095DABB1A18767E25F14E1A564854A7F24553CF1E8439FBCA5842A4ECD18F7D675A2871729EEF98902DB2E676078E685CD2376B56616710B
t+0.012< 000000bd:00:9A9B5967B4503D29F2C4401CB23AA5B515D31C754B02FA182571CD8B873E9721D9F0898D41C6B7338BF74F3D31F4F246C70EBC1211B62A3627F7C2
t+0.012< 000000bd:01:AE3559D00F49599C8A1F53BEAA4B0DE87C02DAC3C9E97FDCFA3506305DFEF20B334BDB429534DF1F5432DDFE7DEBE6FAEDC1BDB6AA3C92A47199D4
t+0.012< 000000bd:02:CE97C7DACA12B50DA7EAECC73E1EA43C9C8F23967CE453338E8FC532005E06CFF5CDA9C0E05ECD8748B94E86D7F3C37382E609FFCA5C3258EBF78A
t+0.012< 000000bd:03:EC5690BB4B5E640B3EC2D8C50B911491690754DC893AE6880442BA5C2EB2E61A0877D553D5395F13FB37D806C9EC9832F3EC0E7D27F4052B37C088
t+0.012< 000000bd:04:65726E7F7AE554CDBA8D2CCD8864A68F2D92275F86136D033A62086699C8EEFE3A5C7DB442D182FC5EAECAE61270753F029C9E88B00C8BEA6E9450
t+0.012< 000000bd:05:075C3E05979B824BDD53CDD9B17CA3978E130DCE16A96C9E59782A44E6BE94ED1AD3F2B16E74FD4BC7CA247846C810D5DB1DA3F1C60F902088BA64
t+0.012< 000000bd:06:6E78F85C92CB4E4439C341848A0BA903527113274C30CA3EF6D9CE1661887AD000732C923E7AD6783D17FCC823A5CB7516DE9C630E66A1043F6F1B
t+0.012< 000000bd:07:A1F79571F7089D89471760BF5577BB1D9A61E80F77C6ABDAD4117BD851EAF3F2E18963D8910062D817C2976C395389D4B471E32B378F060BA081E4
t+0.012< 000000bd:08:F16CD7E34D604626F24688CA5E4A62CA83B5545769C53B94FDCA9A086A1CEC5C88C43FD52486FB16CC83E12ACD43F551F849A8610EE3F50BAD9014
t+0.012< 000000bd:09:18AC007434C4B309E93905FF0688E030562325A71B6E4F7C7D337288E0029CF8AE9D6CE26120EB4A59F04A5F792A90CF4EB5766924C5E6A1F85829
t+0.012< 000000bd:0a:D95AC6D108633EEAC45ED50FB7C659173F83A70ED15C843B8049212142794B1BD311ECDB742AC538889A474060A0579F24FEADF55A3130DB7B51FC
t+0.012< 000000bd:0b:BDCA47D89D58C478CCEF3D0577D84CB738ED0ED8110C850667B7374232883EEF5386C7F0DE8B69AB7AA6B0F27EFCA9B7E9B88FFAC414012BCB386D
t+0.012< 000000bd:0c:FDC0ACEC1332B304103F6DBBB9136BAB92685549510DD84CD1EC4DFDB8856AB54516A25948555D5994CA144EDD80F96FE84EB8395B90852D7DD22A
t+0.012< 000000bd:0d:355794EA9DAB8CF6F3E2534C761D61C4FAE1BE6AC90C220268B38895305ABF65B2534F4FFEDC45F2BE983E34B59FF9AF80B71949C33C4C2BEFD4C0
t+0.012< 000000bd:0e:1F2E7F84E0D3D32FD1AF74C36D0C02A2C1A19B7122528A6B15C6B741B58B01D4BA81589A542CCA25DB3EE9494BEBEB0C8C867DAED8081AEDCED12E
t+0.012< 000000bd:0f:845D305817B1B1B105DD7B2AB8BA130105FEEC118B728F394A975338652566E98296429947F34A4CD0C67788808A8A8589769614E9254D33BCA16B
t+0.012< 000000bd:10:22C6D20B48684DE1B0402BFC10F1739971FE23F687998D000000000000000000000000000000000000000000000000000000000000000000000000
test_LongEcho[143]: sent: 0.163895, received: 0.400035
CHECK_LE fail at test_LongEcho[149]:sent > .075: (continuing -a)
CHECK_LE fail at test_LongEcho[151]:received > .075: (continuing -a)
PASS(test_LongEcho())
t+0.004> 000000bd:81[99]:9B82B2E8B66F8921914FF39C975CEA780C2AA4083B957CD4077AF7FD01908A9C133D84C9AC0EEA3D5DDED9F53AC36D46EE114E29A7CAFDAE44
t+1.001< (timeout)
CHECK_EQ fail at test_Timeout[217]:0 != U2Fob_receiveHidFrame(device, &r, 1.0): (continuing -a)
CHECK_EQ fail at test_Timeout[218]:f.cid != r.cid: (continuing -a)
CHECK_EQ fail at test_Timeout[220]:isError(r, ERR_MSG_TIMEOUT) != true: (continuing -a)
CHECK_LE fail at test_Timeout[224]:measuredTimeout > 1.0: (continuing -a)
PASS(test_Timeout())
t+0.003> 000000bd:81[99]:F4AB458436E1977366601F744B5CD12935C663F934A9E745F710ECC20D9A0601464C857C2D1DEF937D0E07C86AD9F19F9F5498D3FD7F19F58F
t+0.004> 000000bd:01:0063F4AB458436E1977366601F744B5CD12935C663F934A9E745F710ECC20D9A0601464C857C2D1DEF937D0E07C86AD9F19F9F5498D3FD7F19F58F
t+1.001< (timeout)
CHECK_EQ fail at test_WrongSeq[311]:0 != U2Fob_receiveHidFrame(device, &r, 1.0): (continuing -a)
CHECK_EQ fail at test_WrongSeq[312]:f.cid != r.cid: (continuing -a)
CHECK_LT fail at test_WrongSeq[314]:U2Fob_deltaTime(&t) >= .1: (continuing -a)
CHECK_EQ fail at test_WrongSeq[315]:isError(r, ERR_INVALID_SEQ) != true: (continuing -a)
t+0.601< (timeout)
PASS(test_WrongSeq())
t+0.002> 000000bd:81[99]:05B79CA0BD9DE6092362374051CABD5FD286C9AB77684ACC011EC98037BE103C75ACDC334AC23C6D2473AD753E6AD410F09DBB680605340723
t+0.004> 000000bd:81[99]:05B79CA0BD9DE6092362374051CABD5FD286C9AB77684ACC011EC98037BE103C75ACDC334AC23C6D2473AD753E6AD410F09DBB680605340723
t+0.028< 000000bd:bf[1]:040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.601< (timeout)
PASS(test_NotCont())
t+0.003> 000000bd:00:0008FD875ABC9797314400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+1.001< (timeout)
PASS(test_NotFirst())
t+0.003> 000000bd:81[7610]:73648E36A1FB5A14A8D05212A46203421D6B48239F4F469CD6A1586E388AB2ABEE40E18F3B3CA4E30CF6F5B059F8F276633A990289E09F6081
t+1.001< (timeout)
CHECK_EQ fail at test_Limits[185]:0 != U2Fob_receiveHidFrame(device, &r, 1.0): (continuing -a)
CHECK_EQ fail at test_Limits[186]:f.cid != r.cid: (continuing -a)
CHECK_EQ fail at test_Limits[188]:isError(r, ERR_INVALID_LEN) != true: (continuing -a)
PASS(test_Limits())
t+0.003> 000000bd:81[99]:F7CEB981806470C046FFFB82A3DE8E9AD33EF3CC31692F6B0332F5E3D15564C8231D4AA381BA63C7B95E495D3CD7F70F16EADB47530BB2563D
t+0.004> 000000bc:81[99]:F7CEB981806470C046FFFB82A3DE8E9AD33EF3CC31692F6B0332F5E3D15564C8231D4AA381BA63C7B95E495D3CD7F70F16EADB47530BB2563D
t+1.001< (timeout)
CHECK_EQ fail at test_Busy[344]:0 != U2Fob_receiveHidFrame(device, &r, 1.0): (continuing -a)
CHECK_EQ fail at test_Busy[345]:f.cid != r.cid: (continuing -a)
CHECK_LT fail at test_Busy[347]:U2Fob_deltaTime(&t) >= .1: (continuing -a)
CHECK_EQ fail at test_Busy[348]:isError(r, ERR_CHANNEL_BUSY) != true: (continuing -a)
t+1.001< (timeout)
CHECK_EQ fail at test_Busy[352]:0 != U2Fob_receiveHidFrame(device, &r, 1.0): (continuing -a)
CHECK_EQ fail at test_Busy[353]:f.cid != r.cid: (continuing -a)
CHECK_EQ fail at test_Busy[355]:isError(r, ERR_MSG_TIMEOUT) != true: (continuing -a)
PASS(test_Busy())
t+0.001> 000000bd:81[116]:A7390EFC9DD61FBA20C23CDA250394834DF1BF24E8CF3AD2AA8125B5347CF2DBB500D853D7F70DF7BA49D2DF4D66639A5722BE3FF1F9119C7A
t+0.004> 000000bc:81[116]:3651AEB2448A684462BB1B59C8131312E5F35F4B56F9A278B7E16AB0F2062B2857D9DB9B6343E0C5FEFB1FC60E32D8F325373E7B30E0F4E8C1
t+0.004> 000000bc:00:A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6A6
t+0.004> 000000bd:00:A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7
t+0.064< 000000bd:81[116]:A7390EFC9DD61FBA20C23CDA250394834DF1BF24E8CF3AD2AA8125B5347CF2DBB500D853D7F70DF7BA49D2DF4D66639A5722BE3FF1F9119C7A
CHECK_EQ fail at test_Interleave[385]:r.cid != cid1: (continuing -a)
CHECK_EQ fail at test_Interleave[386]:isError(r, ERR_CHANNEL_BUSY) != true: (continuing -a)
t+0.012< 000000bd:00:A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7A7
t+1.001< (timeout)
CHECK_EQ fail at test_Interleave[392]:0 != U2Fob_receiveHidFrame(device, &r, 1.0): (continuing -a)
CHECK_EQ fail at test_Interleave[393]:r.cid != cid0: (continuing -a)
CHECK_EQ fail at test_Interleave[394]:r.cont.data[1] != expected: (continuing -a)
t+0.501< (timeout)
PASS(test_Interleave())
t+0.002> 00000100:81[10]:5E98B364C3DCBB9DB7570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< 00000100:bf[1]:0B0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
CHECK_EQ fail at test_LeadingZero[460]:r.init.cmd != U2FHID_PING: (continuing -a)
CHECK_EQ fail at test_LeadingZero[461]:MSG_LEN(f) != MSG_LEN(r): (continuing -a)
PASS(test_LeadingZero())
t+2.002< (timeout)
PASS(test_Idle(2.0))
t+0.002> 00000000:86[8]:00FA37C6F832E5BE00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< 00000000:bf[1]:0B0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
PASS(test_NothingOnChannel0())
t+0.004> ffffffff:81[8]:411797343DCE73B800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
t+0.024< ffffffff:bf[1]:0B0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
PASS(test_OnlyInitOnBroadcast())
test_Descriptor[617]: DESCRIPTOR: 06D0F10901A1010920150026FF007508954081020921150026FF00750895409102C0
PASS(test_Descriptor())

```

**Comment by liamjm** [comment] 2021-11-02 01:42
Digging into the first failure (test_InitOnNonBroadcastEchoesCID: https://github.com/google/u2f-ref-code/blob/master/u2f-tests/HID/HIDTest.cc#L464)....

In this test, an INIT command with non-broadcast CID is sent. The expectation is that the configured CID is returned. Instead an error is returned (CtapHid::ERR_INVALID_CHANNEL). 
This is "working as implemented":
a) The error is returned [in process_hid_packet()](https://github.com/google/OpenSK/blob/5e682d9e176e936c22fcb963a708ffb0b47a33e6/src/ctap/hid/mod.rs#L172)
b) via [inspecting the command and CID](https://github.com/google/OpenSK/blob/5e682d9e176e936c22fcb963a708ffb0b47a33e6/src/ctap/hid/mod.rs#L339)
c) and [ensuring the CID has been allocated](https://github.com/google/OpenSK/blob/5e682d9e176e936c22fcb963a708ffb0b47a33e6/src/ctap/hid/mod.rs#L344)

However, from what I can tell from the specs, the behavior expected in this test, is not described in the [reference specifications](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-hid-protocol-v1.2-ps-20170411.html#u2fhid_init). The other non-OpenSK device I have passes this test.

So this raises several options:
a) the spec is missing requirements that are generally expected and commonly implemented
b) OpenSK should implement this behavior
c) The reference code should remove this test as it is not a requirement.

**Comment by kaczmarczyck** [comment] 2021-11-03 12:30
Thanks for creating this issue. OpenSK is tested with FIDO's new conformance tool, described [here](https://fidoalliance.org/certification/functional-certification/conformance/). Unfortunately, this tool is closed source. The FIDO Alliance GitHub deprecated the tool you have been testing with (see [About section](https://github.com/fido-alliance/google-u2f-ref-code)).

I agree that we should have more open source, up-to-date testing for U2F, HID and NFC. Ideally from our perspective, they should be integrated into our [Test Tool](https://github.com/google/CTAP2-test-tool). This is on our list of future work.

**Comment by kaczmarczyck** [comment] 2021-11-10 15:59
Closing as working as intended.

**Closed as completed by kaczmarczyck** 2021-11-10 15:59 UTC
Labels: wontfix
