### ISSUE TITLE
launchpadlib 1.10.13 is not installed during setup

### ISSUE THREAD

**Issue by mxi1** [google/OpenSK#343] opened 2021-07-06 01:22 UTC
## Expected Behavior
The `launchpadlib` should be installed.  Can I install the latest lanuchpadlib instead of the specific version "1.10.13"?  Thanks.

## Actual Behavior

> ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.

## Steps to Reproduce the Problem

1.  run the default `setup.sh`, you will see this error.

## Specifications

- Version: the stable version, and the latest commit is 7e5e2a665ff4f9ba68b7e8d098ee2248a3a85bb8
- Platform: Ubuntu 20.04 x86_64

**Comment by kaczmarczyck** [comment] 2021-07-06 22:57
Hi!

I don't find any mention of `launchpadlib` (or `lunchpadlib`, but that's probably a typo?) in our code, or a requirement of version  "1.10.13". Can you point me to where this comes from?

**Comment by mxi1** [comment] 2021-07-07 01:07
Okay, thanks. as you replied, it seems to be one dependency for one pip package required by your shell script. 
I cannot find the previous shell output right now, need to re-run your `setup.sh` script on another clean machine, and I will post the update here. Thanks. :smile:

**Comment by jmichelp** [comment] 2021-08-16 18:14
@mxi1 Any update?

**Comment by mxi1** [comment] 2021-08-17 11:03
> @mxi1 Any update?
It's still there. I googled the error message, and found that the version of `launchpadlib`  is the root cause. Instead, the `testresources` package is.

In order to fix this issue, the `python3-testresources` or `python-testresources` is required before running `./setup.sh`.

**Comment by mxi1** [comment] 2021-08-17 11:04
[ERROR: launchpadlib 1.10.6 requires testresources, which is not installed ](https://gist.github.com/y56/0540d22a1db40dacc7fbbb93c866821e) is one reference hosted on github gist website.

**Comment by kaczmarczyck** [comment] 2021-09-07 06:54
I was unable to reproduce on a freshly installed Debian-based distro.
This seems like a packaging bug in Ubuntu / Debian to me, that might have been fixed? If you think a workaround for your Ubuntu version is worthwhile, feel free to contribute one.

**Comment by mxi1** [comment] 2021-09-08 14:08
Okay, let me have a try.

**Comment by mxi1** [comment] 2021-09-10 03:14
> I was unable to reproduce on a freshly installed Debian-based distro.
> This seems like a packaging bug in Ubuntu / Debian to me, that might have been fixed? If you think a workaround for your Ubuntu version is worthwhile, feel free to contribute one.

Please check this PR: https://github.com/google/OpenSK/pull/376

**Comment by kaczmarczyck** [comment] 2021-09-10 13:48
Feel free to close this issue if it's resolved on bugfix!

**Closed as completed** 2021-09-11 04:46 UTC
